name: GoLinux
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Some parameters
      run: |
        lsb_release -a
        cat etc/debian_release || true
        sysctl fs.file-max || true

    - name: Vet
      run: go vet ./...

    - name: Build
      run: go build -v ./...

    - name: Run
      run: go test -v ./...

    - name: Check parameter changes
      run: |
        sysctl fs.file-max || true
